[package]
name = "alumet"
version = "0.9.2"
edition.workspace = true
repository.workspace = true
rust-version = "1.89"

description = "Modular framework for hardware and software measurement (including energy consumption and more)."
license = " EUPL-1.2"
homepage = "https://alumet.dev"
keywords = ["rapl", "energy", "monitoring", "profiling"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
# enables test module
test = []

[dependencies]
toml = { workspace = true, features = ["preserve_order"] }
libc = "0.2.158"
log.workspace = true
anyhow.workspace = true
rustc-hash.workspace = true
serde.workspace = true
smallvec = { version = "1.13.2", features = ["union"] }
tokio = { workspace = true, features = ["time", "rt", "rt-multi-thread", "macros", "signal", "tracing"] }
tokio-stream = { version = "0.1.17", features = ["sync"] }
tokio-util = "0.7.17"
indoc = "2.0.5"
thiserror.workspace = true
futures = "0.3.30"
ordered-float = "4.6.0"
num_enum = "0.7.3"
nc = "0.9"
pin-project-lite = "0.2.16"

# Dependencies for Linux builds only.
[target.'cfg(target_os = "linux")'.dependencies]
tokio-timerfd = "0.2.0"

# Dev dependencies for tests.
[dev-dependencies]
console-subscriber = "0.5.0"
env_logger.workspace = true
pretty_assertions = "1.4.1"
serde = { workspace = true, features = ["derive"] }
serial_test = "3.2.0"

[lints]
workspace = true
