---
name: Check documentation
on: [pull_request, push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Spell check everything
        uses: streetsidesoftware/cspell-action@v6
        with:
          root: .
          incremental_files_only: true
          config: .cspell.json
          verbose: true
      - uses: DavidAnson/markdownlint-cli2-action@v19
        name: Markdown lint
        with:
          config: .markdownlint.jsonc
          globs: |
            *.md
            **/*.md
